apiVersion: v1
kind: Service
metadata:
  name: author-mongodb-service
spec:
  selector:
    app: author-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP