apiVersion: v1
kind: ConfigMap
metadata:
  name: author-mongodb-config
data:
  mongod.conf: |
    
    storage:
      dbPath: /data/authors/db
    systemLog:
      destination: file
      path: /data/authors/log
      verbosity: 2
    net:
      bindIp: 0.0.0.0
      port: 27017
