apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-mongodb
  template:
    metadata:
      labels:
        app: author-mongodb
    spec:
      containers:
        - name: author-mongodb
          image: mongo
          command:
            - "mongod"
          args:
              - "--config"
              - "/etc/mongod.conf"
              - "--bind_ip"
              - "0.0.0.0"
              - "--port"
              - "27017"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: author-mongodb-storage
              mountPath: /data/authors/db
            - name: author-mongodb-config
              mountPath: /etc/mongod.conf
              subPath: mongod.conf
      volumes:
        - name: author-mongodb-storage
          persistentVolumeClaim:
            claimName: author-mongodb-pvc
        - name: author-mongodb-config
          configMap:
            name: author-mongodb-config
