apiVersion: v1
kind: ConfigMap
metadata:
  name: author-mongodb-config
data:
  mongod.conf: |
    dbPath: /data/authors/db
    logPath: /data/authors/log
    replication:
      replSetName: my-replica-set
