apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksapifeatureoff
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: booksapifeatureoff
  template:
    metadata:
      labels:
        app: booksapifeatureoff
    spec:
      containers:
      - name: booksapifeatureoff
        image: scupak/booksapi:main-BooksApi
        imagePullPolicy: Always
        env:
        - name: GREETING_FEATURE_FLAG
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: booksapifeatureoff
  namespace: default
spec:
  type: NodePort
  selector:
    app: booksapifeatureoff
  ports:
  - port: 80
    nodePort: 31004