apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksapi
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: booksapi
  template:
    metadata:
      labels:
        app: booksapi
    spec:
      containers:
      - name: booksapi
        image: scupak/booksapi:main-BooksApi
        imagePullPolicy: Always
        env:
        - name: GREETING_FEATURE_FLAG
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: booksapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: booksapi
  ports:
  - port: 80
    nodePort: 31003