apiVersion: v1
kind: ConfigMap
metadata:
  name: book-mongodb-config
data:
  mongod.conf: |
    storage:  
        dbPath: /data/books/db
    systemLog:
        destination: file
        path: /data/books/log
        verbosity: 2
    net:
      bindIp: 0.0.0.0
      port: 27017
