apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booksapi
  template:
    metadata:
      labels:
        app: booksapi
    spec:
      containers:
      - name: booksapi
        image: scupak/booksapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: booksapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: booksapi
  ports:
  - port: 80
    nodePort: 31003