name: .NET Tests and Docker Push
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
jobs:
  test-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DlsExamProject
    strategy:
      matrix:
        application: [AuthorsApi]
        IMAGE_NAME: [scupak/authorsapi]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build ${{ matrix.application }} --no-restore

     # - name: Run tests
     #   run: dotnet test ${{ matrix.application }} --no-build --verbosity normal

      - name: Build Docker image
        working-directory: ./DlsExamProject/AuthorsApi
        run: |
          docker build ${{ matrix.application }} \
            --tag $REGISTRY/${{ matrix.IMAGE_NAME }}:latest

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            --username ${{ secrets.DOCKER_USERNAME }} \
            --password-stdin

      - name: Push Docker image
        run: |
          docker push $REGISTRY/${{ matrix.IMAGE_NAME }}:latest
