name: Publish Docker images
env:
  PROJECT_TO_REPO_MAP: |
    {
      "AuthorsApi": "authorsapi",
      "BooksApi": "booksapi"
    }
on:
   workflow_dispatch:
   push:
    branches:
      - main
jobs:
  test:
    name: .NET Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
        
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['AuthorsApi','BooksApi']
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: scupak/${{ fromJson(env.PROJECT_TO_REPO_MAP)[matrix.project] }}
      
      - name: Build and push Docker image for ${{ matrix.project }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./DlsExamProject
          file: ./DlsExamProject/${{ matrix.project }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ matrix.project }}
          labels: ${{ steps.meta.outputs.labels }}
