name: Publish Docker images
on:
   workflow_dispatch:
   push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['AuthorsApi']
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
      
      - name: Build and push Docker image for ${{ matrix.project }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./DlsExamProject
          file: ./DlsExamProject/${{ matrix.project }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ matrix.project }}
          labels: ${{ steps.meta.outputs.labels }}
